### ISSUE TITLE
Close/Hide method to dispose of the dialog

### ISSUE THREAD

**Issue by bradmartin** [enchev/nativescript-dialog#1]
Are there any methods to remove the dialog from the UI? I didn't see anything in the .js files to do this. Thanks. 

Oh and a huge :+1:  for this, I've been trying to achieve this for a couple days with no luck.

**Comment by enchev** [comment]
Hey @bradmartin,

I've pushed new version to npm - let me know will this work for you!

Thanks

**Comment by bradmartin** [comment]
@enchev - thanks for adding that. It just seemed necessary to be able to manipulate the show/hide with a method exposed.
