### ISSUE TITLE
When there's no message set, there's whitespace where the message should be

### ISSUE THREAD

**Issue by lscown** [enchev/nativescript-dialog#4]
Hey there,

So I see when there's no message set that the message field is still initialised on both iOS and Android with an empty string. This leaves a fairly obvious space between the title and the nativeView. The way I fixed it was by checking whether the message was set, and then setting the message rather than initialising it with an empty string. So:

for example on Android, rather than:

``` js
alert.setMessage(options.message || "");
```

I use:

``` js
if (options.message) {
  alert.setMessage(options.message);
}
```

I'm not exactly sure if it's default behaviour on iOS, as removing the message doesn't seem to change anything.

**Comment by enchev** [comment]
Thanks @lscown! I've updated the module in npmjs.org as well.

**Comment by lscown** [comment]
Awesome, great to hear @enchev :-)
