### ISSUE TITLE
Question: position of message/indicator?

### ISSUE THREAD

**Issue by bradmartin** [enchev/nativescript-dialog#7]
Can the message and indicator be together on the same "row"? I'll attach an image when I get to my computer but they're on the same line in the apps I use. Trello, Twitter, Facebook. If you don't have the time to look into this I'll see about the android side, iOS I have no clue.

**Comment by bradmartin** [comment]
![screenshot_2015-12-10-20-45-51](https://cloud.githubusercontent.com/assets/6006148/11735331/9f3f0bbe-9f85-11e5-8a9b-18b70be72544.png)

**Comment by enchev** [comment]
Hey @bradmartin,

You can do this if you construct nativeView with UILabel and UIActivityIndicatorView and do not use the built-in message.

**Comment by bradmartin** [comment]
Thanks.
